In [1]:
##Importuri necesare

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import re

In [2]:
import pandas as pd
data_path = ''
train_data_df = pd.read_csv(os.path.join(data_path, 'train_data.csv'))
train_data_df

language                                               text     label
0           dansk  \nDette er et fremragende initiativ, og jeg st...   Ireland
1           dansk  \nHr. formand, jeg er sikker på, at alle her e...   Ireland
2           dansk  \nHr. formand, folk på den nordlige halvkugle ...   England
3           dansk  \nHr. formand, med forbehold af nogle få ændri...   England
4           dansk  \n\n   - Hr. formand, jeg må protestere mod de...   England
...           ...                                                ...       ...
41565  Nederlands  \nMijnheer de Voorzitter, juridisch gezien is ...   England
41566  Nederlands  \n\n   .  Mijnheer de Voorzitter, het is niet ...  Scotland
41567  Nederlands  \nAls afgevaardigde van Ierland, het 'voedsele...   Ireland
41568  Nederlands  \nMijnheer de Voorzitter, het is niet onterech...   England
41569  Nederlands  \n\n   - Stelt u zich voor dat een ander wetge...   Ireland

[41570 rows x 3 columns]

In [3]:
## Codificarea etichetelor din string in int

In [4]:
#Exercitiu: codificam etichetele / labels in valori cu numere intregi dela 0 la N
# codificam etichetele / labels in valori cu numere intregi dela 0 la N
# ar putea fi exercitiu la clasa ca sa se obisnuiasca cu dictionare
etichete_unice = train_data_df['label'].unique()
print(etichete_unice)
label2id = {}
id2label = {}
for idx, eticheta in enumerate(etichete_unice):
    label2id[eticheta] = idx
    id2label[idx] = eticheta

print(label2id)
print(id2label)

['Ireland' 'England' 'Scotland']
{'Ireland': 0, 'England': 1, 'Scotland': 2}
{0: 'Ireland', 1: 'England', 2: 'Scotland'}


In [5]:
y_labels = []
for eticheta in train_data_df['label']:
    y_labels.append(label2id[eticheta])
y_labels = np.array(y_labels)

print(y_labels[:100])

[0 0 1 1 1 0 1 1 1 2 1 0 2 2 2 1 1 0 1 1 1 2 2 1 1 1 0 2 1 0 1 1 2 0 1 1 0
 1 1 2 1 1 0 0 1 0 2 1 1 0 1 0 1 2 2 1 1 0 1 1 2 1 0 0 0 2 2 2 2 0 1 1 1 0
 1 2 1 2 1 0 1 1 1 2 1 0 2 2 1 1 0 1 1 1 1 0 2 1 2 1]


In [7]:
## Pre-procesarea datelor

In [6]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

exemple_italian = train_data_df[train_data_df['language'] == 'italiano']
print(exemple_italian)

       language                                               text     label
24942  italiano  \nSi tratta di un'eccellente iniziativa e cond...   Ireland
24943  italiano  \nSignor Presidente, tutti i presenti sanno ce...   Ireland
24944  italiano  \nSignor Presidente, nel Nord del mondo si pen...   England
24945  italiano  \nSignor Presidente, fatti salvi alcuni emenda...   England
24946  italiano  \n\n   – Signor Presidente, desidero protestar...   England
...         ...                                                ...       ...
33251  italiano  \nSignor Presidente, l' obiettivo giuridico de...   England
33252  italiano  \n\n    Signor Presidente, non spetta a me tog...  Scotland
33253  italiano  \nVenendo dall'Irlanda, l'"isola del cibo", so...   Ireland
33254  italiano  \nSignor Presidente, è opportuno che io interv...   England
33255  italiano  \n\n   – E’ d’accordo il Presidente in carica ...   Ireland

[8314 rows x 3 columns]


[nltk_data] Downloading package punkt to /home/dorian/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [7]:
def proceseaza(text):
    text = re.sub("[-–.,;:!\’?\"\'\/()_*=`]", "", text)
    text = text.lower()
    text = word_tokenize(text)
    return text

In [8]:
exemplu = "– Señor Pres’idente, doy las gracias al Comisario, no solo por venir hoy aquí a escuchar el debate, sino también por la ayuda que creo que prestó a los diputados en Ginebra la semana pasada. No pude estar allí, pero ellos expresaron su agradecimiento por la forma en que los mantuvo informados."
exemplu = re.sub("[-–.,;:!’?\"\'\/()_*=`]", "", exemplu)
exemplu = word_tokenize(exemplu)

exemplu

['Señor',
 'Presidente',
 'doy',
 'las',
 'gracias',
 'al',
 'Comisario',
 'no',
 'solo',
 'por',
 'venir',
 'hoy',
 'aquí',
 'a',
 'escuchar',
 'el',
 'debate',
 'sino',
 'también',
 'por',
 'la',
 'ayuda',
 'que',
 'creo',
 'que',
 'prestó',
 'a',
 'los',
 'diputados',
 'en',
 'Ginebra',
 'la',
 'semana',
 'pasada',
 'No',
 'pude',
 'estar',
 'allí',
 'pero',
 'ellos',
 'expresaron',
 'su',
 'agradecimiento',
 'por',
 'la',
 'forma',
 'en',
 'que',
 'los',
 'mantuvo',
 'informados']

In [9]:
# Exercitiu: aplicati functia pe fiecare exemplu de antrenare
#data = []
data = train_data_df['text'].apply(lambda text: proceseaza(text))
print(data[33255])
print(type(data))

['e', 'daccordo', 'il', 'presidente', 'in', 'carica', 'del', 'consiglio', 'che', 'se', 'una', 'qualunque', 'altra', 'legislatura', 'nellunione', 'europea', 'adottasse', 'decisioni', 'e', 'pubblicasse', 'i', 'verbali', 'e', 'le', 'note', 'relative', 'alle', 'discussioni', 'e', 'si', 'offrisse', 'di', 'caricare', 'le', 'informazioni', 'su', 'un', 'sito', 'la', 'gente', 'penserebbe', 'che', 'si', 'tratta', 'di', 'un', 'atteggiamento', 'assai', 'poco', 'democratico', 'e', 'limpido', 'non', 'è', 'forse', 'giunto', 'il', 'momento', 'una', 'volta', 'per', 'tutte', 'di', 'fare', 'in', 'modo', 'che', 'quando', 'il', 'consiglio', 'dei', 'ministri', 'agisce', 'in', 'qualità', 'di', 'legislatore', 'le', 'sue', 'riunioni', 'siano', 'pubbliche', 'apprezzo', 'i', 'progressi', 'compiuti', 'ma', 'è', 'totalmente', 'inaccettabile', 'che', 'nel', 'xxi', 'secolo', 'si', 'continui', 'a', 'legiferare', 'in', 'questa', 'maniera']
<class 'pandas.core.series.Series'>


In [50]:
from sklearn.model_selection import train_test_split

train_data, test_data, y_train, y_test = train_test_split(data, y_labels, test_size=0.33, random_state=42)

train_data, valid_data, y_train, y_valid = train_test_split(train_data, y_train, test_size=0.33, random_state = 42)

In [51]:
np.bincount(y_train)

array([ 4781, 10168,  3711])

In [13]:
train_data2 = train_data.map(' '.join)
test_data2= test_data.map(' '.join)
valid_data2 = valid_data.map(' '.join)

train_data2

8456     herr präsident die erschreckenden bilder und d...
17637    por escrito he votado a favor de este informe ...
32343    signor presidente vorrei associarmi ai collegh...
39137    schriftelijk en ik heb vóór dit verslag gestem...
5171     hr formand jeg vil gerne takke ordførerne for ...
                               ...                        
18231    señor presidente la perspectiva de adhesión a ...
31516    mi congratulo con l onorevole papayannakis per...
38432    mijnheer de voorzitter ik verwelkom het versla...
15       hr formand i laekenerklæringen blev euinstitut...
9788     schriftlich en die britischen konservativen ha...
Name: text, Length: 18660, dtype: object

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features = 75000, tokenizer = lambda x: x, preprocessor = lambda x: x, max_df= 0.25)

vectorizer.fit(train_data)

print(vectorizer.vocabulary_)

/home/dorian/anaconda3/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:516: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


{'herr': 30932, 'präsident': 52393, 'parlamentarischen': 48572, 'tradition': 65462, 'aus': 6489, 'ich': 32002, 'komme': 36784, 'mussten': 43470, 'wir': 73170, 'uns': 67959, 'nicht': 44533, 'auf': 6246, 'minuten': 42543, 'beschränken': 9091, 'sehr': 58702, 'oft': 45584, 'wurden': 73412, 'kurzfristig': 37776, 'gebeten': 27158, 'plenarsaal': 50193, 'zu': 73952, 'und': 67496, 'eine': 19822, 'stunde': 62160, 'oder': 45467, 'so': 60126, 'allen': 3263, 'möglichen': 43648, 'unbedeutenden': 67479, 'themen': 64528, 'sprechen': 61107, 'hier': 31065, 'ist': 35192, 'situation': 59684, 'anders': 3929, 'freue': 26270, 'mich': 42073, 'einen': 19824, 'beitrag': 8292, 'diesem': 17573, 'thema': 64521, 'leisten': 39056, 'können': 38006, 'denn': 16664, 'gehöre': 27546, 'zwar': 74294, 'dem': 16504, 'zuständigen': 74212, 'ausschuss': 6770, 'an': 3801, 'habe': 30061, 'mir': 42554, 'aber': 1001, 'dennoch': 16668, 'über': 74812, 'gegenstand': 27455, 'debatte': 15783, 'gedanken': 27277, 'gemacht': 27732, 'als': 

In [42]:
X_train = vectorizer.transform(train_data)
X_valid = vectorizer.transform(valid_data)
X_test = vectorizer.transform(test_data)

In [43]:
from sklearn import preprocessing

X_train = preprocessing.normalize(X_train, axis = 1)
X_valid = preprocessing.normalize(X_valid, axis = 1)
X_test = preprocessing.normalize(X_test, axis = 1)

In [44]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

print('fitting...')
clf = OneVsRestClassifier(SVC()).fit(X_train, y_train)

print('predicting...')
y_pred = clf.predict(X_valid)
print(accuracy_score(y_valid,y_pred))


fitting...
predicting...
0.6537917528016538


from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

model = MultinomialNB()

param={'alpha': [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000]}
    
clf=GridSearchCV(model,param,cv=10,return_train_score=True)  

print('Fitting...')
clf.fit(X_train, y_train)

print('Predicting...')
y_pred = clf.predict(X_valid)
print((y_pred == y_valid).mean()*100)

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(C=1, kernel='linear', gamma='auto')

print('fitting...')
clf.fit(X_train, y_train)


print('predicting...')
y_pred = clf.predict(X_valid)
print(accuracy_score(y_valid, y_pred))

In [18]:
data_path = ''
test_data_df = pd.read_csv(os.path.join(data_path, 'test_data.csv'))
test_data_df

text
0      \n\n   Hr. formand, selv om vi i høj grad symp...
1      \n\n   Quiero dejar constancia de mi apoyo a e...
2      \n\n   . – El comercio ilegal de riñones human...
3      \nSignor Presidente, per introdurre una nota d...
4      \nJeg stemte for meddelelsen af decharge til f...
...                                                  ...
13855  \nschriftlich. - Dieser Bericht handelt von wi...
13856  \n\n   Signor Presidente, desidero ringraziare...
13857  \n. (EN) Ich unterstütze den Bericht von Herrn...
13858  \n\n   – Mijnheer de Voorzitter, ik ben verheu...
13859  \nJeg stemte for at bekræfte hr. Trichet som f...

[13860 rows x 1 columns]

In [19]:
test = test_data_df['text'].apply(lambda text: proceseaza(text))

In [20]:
test

0        [hr, formand, selv, om, vi, i, høj, grad, symp...
1        [quiero, dejar, constancia, de, mi, apoyo, a, ...
2        [el, comercio, ilegal, de, riñones, humanos, s...
3        [signor, presidente, per, introdurre, una, not...
4        [jeg, stemte, for, meddelelsen, af, decharge, ...
                               ...                        
13855    [schriftlich, dieser, bericht, handelt, von, w...
13856    [signor, presidente, desidero, ringraziare, il...
13857    [en, ich, unterstütze, den, bericht, von, herr...
13858    [mijnheer, de, voorzitter, ik, ben, verheugd, ...
13859    [jeg, stemte, for, at, bekræfte, hr, trichet, ...
Name: text, Length: 13860, dtype: object

In [21]:

print(vectorizer.vocabulary_)

{'herr': 31298, 'präsident': 52657, 'erschreckenden': 22188, 'bilder': 10008, 'und': 67491, 'tragischen': 65358, 'persönlichen': 49942, 'geschichten': 28789, 'nach': 44680, 'dem': 16477, 'erdbeben': 21817, 'vom': 71538, '8': 556, 'oktober': 46626, 'mögen': 44599, 'von': 71539, 'unseren': 67958, 'fernsehschirmen': 24524, 'titelseiten': 64627, 'unserer': 67959, 'zeitungen': 73718, 'verschwunden': 70112, 'sein': 58287, 'aber': 964, 'vergessen': 69511, 'wir': 73221, 'nicht': 45488, 'dass': 15522, 'dringliche': 19210, 'hilfe': 31477, 'noch': 45636, 'genauso': 28260, 'notwendig': 45902, 'ist': 35552, 'vor': 71744, 'allem': 3138, 'wegen': 72615, 'des': 16833, 'bereits': 8813, 'jetzt': 35788, 'gibt': 29422, '74': 543, '000': 4, 'tote': 65164, 'zu': 73994, 'bringen': 10722, 'ein': 20141, 'wettlauf': 73018, 'mit': 43651, 'zeit': 73696, 'pakistanische': 48781, 'regierung': 54452, 'hat': 30858, 'verursachten': 70415, 'kosten': 37504, 'fünf': 27268, 'milliarden': 43290, 'usdollar': 68284, 'eu': 230

In [22]:
Kaggle_test = vectorizer.transform(test)

Kaggle_test = preprocessing.normalize(Kaggle_test, axis = 1)

In [23]:
print('predicting...')
Kaggle_pred = clf.predict(Kaggle_test)

Kaggle_pred

predicting...


array([1, 1, 1, ..., 1, 1, 1])

In [24]:
np.bincount(Kaggle_pred)

array([ 1360, 11461,  1039])

In [25]:
Kaggle_pred = Kaggle_pred[:13860]

converter = lambda x: id2label[x]
vfunc = np.vectorize(converter)

Kaggle_pred = vfunc(Kaggle_pred)

Kaggle_pred

array(['England', 'England', 'England', ..., 'England', 'England',
       'England'], dtype='<U8')

In [26]:
output_df = pd.DataFrame(Kaggle_pred, columns=['label'])
output_df.index.name = 'id'
output_df.index += 1
output_df.to_csv('output2.csv')